name: Test build docker image
on: [push, pull_request, workflow_dispatch]
jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docker image
        run: docker build .
